import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, isSupabaseEnabled } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

// Domain types kept local — types.ts is auto-generated by Lovable Cloud and
// might not yet reflect the new tables; we cast on the client boundary only.
export type HelpFeedPost = {
  id: string;
  author_id: string;
  content: string;
  image_url: string | null;
  image_signed_url: string | null;
  created_at: string;
  author_name: string;
  author_avatar: string | null;
  likes_count: number;
  comments_count: number;
  liked_by_me: boolean;
};

export type HelpFeedComment = {
  id: string;
  post_id: string;
  author_id: string;
  content: string;
  created_at: string;
  author_name: string;
  author_avatar: string | null;
};

export type HelpFeedTutorial = {
  id: string;
  title: string;
  body_md: string;
  order_index: number;
  created_at: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Supabase types auto-gen may lag
const sb = supabase as any;

const MEDIA_BUCKET = "help-feed-media";
const MAX_IMAGE_BYTES = 8 * 1024 * 1024;
const ALLOWED_MIME = new Set(["image/jpeg", "image/png", "image/webp"]);

const extFromMime = (mime: string): string => {
  if (mime === "image/jpeg") return "jpg";
  if (mime === "image/png") return "png";
  if (mime === "image/webp") return "webp";
  return "bin";
};

async function signImage(path: string | null): Promise<string | null> {
  if (!path) return null;
  if (/^https?:\/\//.test(path)) return path;
  const { data } = await sb.storage.from(MEDIA_BUCKET).createSignedUrl(path, 3600);
  return data?.signedUrl ?? null;
}

export function useHelpFeed() {
  const { user } = useAuth();
  const [isAdmin, setIsAdmin] = useState(false);
  const [posts, setPosts] = useState<HelpFeedPost[]>([]);
  const [tutorials, setTutorials] = useState<HelpFeedTutorial[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const refreshAdmin = useCallback(async () => {
    if (!user || !isSupabaseEnabled) {
      setIsAdmin(false);
      return;
    }
    const { data } = await sb
      .from("profiles")
      .select("is_admin")
      .eq("user_id", user.id)
      .maybeSingle();
    setIsAdmin(Boolean(data?.is_admin));
  }, [user]);

  const loadFeed = useCallback(async () => {
    if (!isSupabaseEnabled) {
      setLoading(false);
      return;
    }
    setError(null);
    try {
      const { data: rawPosts, error: postsErr } = await sb
        .from("help_feed_posts")
        .select("id, author_id, content, image_url, created_at")
        .order("created_at", { ascending: false })
        .limit(50);
      if (postsErr) throw postsErr;

      const rows = (rawPosts ?? []) as Array<{
        id: string; author_id: string; content: string;
        image_url: string | null; created_at: string;
      }>;

      if (rows.length === 0) {
        setPosts([]);
        setLoading(false);
        return;
      }

      const authorIds = Array.from(new Set(rows.map((r) => r.author_id)));
      const postIds = rows.map((r) => r.id);

      const [profRes, likesRes, myLikesRes, commentsRes] = await Promise.all([
        sb.from("profiles").select("user_id, display_name, avatar_url").in("user_id", authorIds),
        sb.from("help_feed_likes").select("post_id").in("post_id", postIds),
        user
          ? sb.from("help_feed_likes").select("post_id").eq("user_id", user.id).in("post_id", postIds)
          : Promise.resolve({ data: [] as { post_id: string }[] }),
        sb.from("help_feed_comments").select("post_id").in("post_id", postIds),
      ]);

      const profileMap = new Map<string, { display_name: string | null; avatar_url: string | null }>();
      for (const p of (profRes.data ?? []) as Array<{ user_id: string; display_name: string | null; avatar_url: string | null }>) {
        profileMap.set(p.user_id, { display_name: p.display_name, avatar_url: p.avatar_url });
      }

      const likesCount = new Map<string, number>();
      for (const l of (likesRes.data ?? []) as Array<{ post_id: string }>) {
        likesCount.set(l.post_id, (likesCount.get(l.post_id) ?? 0) + 1);
      }
      const commentsCount = new Map<string, number>();
      for (const c of (commentsRes.data ?? []) as Array<{ post_id: string }>) {
        commentsCount.set(c.post_id, (commentsCount.get(c.post_id) ?? 0) + 1);
      }
      const myLikes = new Set<string>(
        ((myLikesRes.data ?? []) as Array<{ post_id: string }>).map((r) => r.post_id)
      );

      const signed = await Promise.all(rows.map((r) => signImage(r.image_url)));

      const composed: HelpFeedPost[] = rows.map((r, i) => {
        const prof = profileMap.get(r.author_id);
        return {
          id: r.id,
          author_id: r.author_id,
          content: r.content,
          image_url: r.image_url,
          image_signed_url: signed[i],
          created_at: r.created_at,
          author_name: prof?.display_name ?? "Usuario",
          author_avatar: prof?.avatar_url ?? null,
          likes_count: likesCount.get(r.id) ?? 0,
          comments_count: commentsCount.get(r.id) ?? 0,
          liked_by_me: myLikes.has(r.id),
        };
      });

      setPosts(composed);
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Erro ao carregar o feed";
      setError(msg);
    } finally {
      setLoading(false);
    }
  }, [user]);

  const loadTutorials = useCallback(async () => {
    if (!isSupabaseEnabled) return;
    const { data } = await sb
      .from("help_feed_tutorials")
      .select("id, title, body_md, order_index, created_at")
      .order("order_index", { ascending: true })
      .order("created_at", { ascending: false });
    setTutorials((data ?? []) as HelpFeedTutorial[]);
  }, []);

  useEffect(() => {
    void refreshAdmin();
    void loadFeed();
    void loadTutorials();
  }, [refreshAdmin, loadFeed, loadTutorials]);

  useEffect(() => {
    if (!isSupabaseEnabled) return;
    const ch = sb
      .channel("help-feed")
      .on("postgres_changes", { event: "*", schema: "public", table: "help_feed_posts" }, () => void loadFeed())
      .on("postgres_changes", { event: "*", schema: "public", table: "help_feed_likes" }, () => void loadFeed())
      .on("postgres_changes", { event: "*", schema: "public", table: "help_feed_comments" }, () => void loadFeed())
      .subscribe();
    return () => {
      void sb.removeChannel(ch);
    };
  }, [loadFeed]);

  const toggleLike = useCallback(
    async (postId: string) => {
      if (!user) return;
      const post = posts.find((p) => p.id === postId);
      if (!post) return;
      // optimistic
      setPosts((prev) =>
        prev.map((p) =>
          p.id === postId
            ? {
                ...p,
                liked_by_me: !p.liked_by_me,
                likes_count: p.likes_count + (p.liked_by_me ? -1 : 1),
              }
            : p
        )
      );
      if (post.liked_by_me) {
        await sb.from("help_feed_likes").delete().eq("post_id", postId).eq("user_id", user.id);
      } else {
        await sb.from("help_feed_likes").insert({ post_id: postId, user_id: user.id });
      }
    },
    [posts, user]
  );

  const loadComments = useCallback(async (postId: string): Promise<HelpFeedComment[]> => {
    const { data, error: cErr } = await sb
      .from("help_feed_comments")
      .select("id, post_id, author_id, content, created_at")
      .eq("post_id", postId)
      .order("created_at", { ascending: true });
    if (cErr) throw cErr;
    const rows = (data ?? []) as Array<{
      id: string; post_id: string; author_id: string; content: string; created_at: string;
    }>;
    if (rows.length === 0) return [];
    const authorIds = Array.from(new Set(rows.map((r) => r.author_id)));
    const { data: profs } = await sb
      .from("profiles")
      .select("user_id, display_name, avatar_url")
      .in("user_id", authorIds);
    const profMap = new Map<string, { display_name: string | null; avatar_url: string | null }>();
    for (const p of (profs ?? []) as Array<{ user_id: string; display_name: string | null; avatar_url: string | null }>) {
      profMap.set(p.user_id, { display_name: p.display_name, avatar_url: p.avatar_url });
    }
    return rows.map((r) => {
      const prof = profMap.get(r.author_id);
      return {
        ...r,
        author_name: prof?.display_name ?? "Usuario",
        author_avatar: prof?.avatar_url ?? null,
      };
    });
  }, []);

  const addComment = useCallback(
    async (postId: string, content: string) => {
      if (!user) throw new Error("Faça login para comentar.");
      const clean = content.trim().slice(0, 500);
      if (!clean) throw new Error("O comentário não pode ficar em branco.");
      const { error: iErr } = await sb
        .from("help_feed_comments")
        .insert({ post_id: postId, author_id: user.id, content: clean });
      if (iErr) throw iErr;
      await loadFeed();
    },
    [loadFeed, user]
  );

  const createPost = useCallback(
    async (opts: { content: string; file?: File | null }) => {
      if (!user) throw new Error("Faça login.");
      if (!isAdmin) throw new Error("Apenas administradores podem publicar.");
      const cleanContent = opts.content.trim().slice(0, 2000);
      if (!cleanContent && !opts.file) throw new Error("Escreva algo ou anexe uma imagem.");

      let uploadedPath: string | null = null;
      if (opts.file) {
        if (!ALLOWED_MIME.has(opts.file.type)) {
          throw new Error("Formato inválido. Use JPEG, PNG ou WebP.");
        }
        if (opts.file.size > MAX_IMAGE_BYTES) {
          throw new Error("Imagem acima de 8 MB.");
        }
        const path = `${user.id}/${crypto.randomUUID()}.${extFromMime(opts.file.type)}`;
        const { error: upErr } = await sb.storage
          .from(MEDIA_BUCKET)
          .upload(path, opts.file, { contentType: opts.file.type, upsert: false });
        if (upErr) throw new Error(`Falha no upload: ${upErr.message}`);
        uploadedPath = path;
      }

      const { error: insErr } = await sb.from("help_feed_posts").insert({
        author_id: user.id,
        content: cleanContent || "",
        image_url: uploadedPath,
      });
      if (insErr) {
        if (uploadedPath) {
          await sb.storage.from(MEDIA_BUCKET).remove([uploadedPath]).catch(() => undefined);
        }
        throw new Error(`Falha ao publicar: ${insErr.message}`);
      }
      await loadFeed();
    },
    [isAdmin, loadFeed, user]
  );

  const updatePost = useCallback(
    async (postId: string, content: string) => {
      if (!isAdmin) throw new Error("Apenas administradores podem editar publicações.");
      const cleanContent = content.trim().slice(0, 2000);
      if (!cleanContent) throw new Error("A publicação não pode ficar em branco.");
      const { error: updateErr } = await sb
        .from("help_feed_posts")
        .update({ content: cleanContent })
        .eq("id", postId);
      if (updateErr) throw new Error(`Falha ao editar: ${updateErr.message}`);
      await loadFeed();
    },
    [isAdmin, loadFeed]
  );

  const deletePost = useCallback(
    async (postId: string) => {
      if (!isAdmin) throw new Error("Apenas administradores podem excluir publicações.");
      const post = posts.find((row) => row.id === postId);
      if (!post) throw new Error("Publicação não encontrada.");
      const { error: deleteErr } = await sb.from("help_feed_posts").delete().eq("id", postId);
      if (deleteErr) throw new Error(`Falha ao excluir: ${deleteErr.message}`);
      if (post.image_url && !/^https?:\/\//.test(post.image_url)) {
        const { error: storageErr } = await sb.storage.from(MEDIA_BUCKET).remove([post.image_url]);
        if (storageErr) {
          console.warn("Não foi possível remover a imagem da publicação excluída:", storageErr.message);
        }
      }
      await loadFeed();
    },
    [isAdmin, loadFeed, posts]
  );

  const createTutorial = useCallback(
    async (title: string, body: string) => {
      if (!isAdmin) throw new Error("Apenas administradores podem criar tutoriais.");
      const t = title.trim().slice(0, 160);
      const b = body.trim().slice(0, 8000);
      if (!t || !b) throw new Error("Título e conteúdo obrigatórios.");
      const { error: iErr } = await sb.from("help_feed_tutorials").insert({ title: t, body_md: b });
      if (iErr) throw iErr;
      await loadTutorials();
    },
    [isAdmin, loadTutorials]
  );

  const value = useMemo(
    () => ({
      isAdmin,
      posts,
      tutorials,
      loading,
      error,
      toggleLike,
      loadComments,
      addComment,
      createPost,
      updatePost,
      deletePost,
      createTutorial,
      refresh: loadFeed,
    }),
    [isAdmin, posts, tutorials, loading, error, toggleLike, loadComments, addComment, createPost, updatePost, deletePost, createTutorial, loadFeed]
  );

  return value;
}
