import type { CSSProperties } from "react";

export const styles = {
  sidebar: {
    width: 268,
    height: "100dvh",
    maxHeight: "100dvh",
    minHeight: 0,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
    boxSizing: "border-box",
    padding: "30px 16px 18px",
    borderRadius: 0,
    border: "1px solid #E5E7EB",
    background: "#F9FAFB",
    color: "#0A0A0A",
    boxShadow: "none",
  } satisfies CSSProperties,
  scrollArea: {
    // Navegação e bloco inferior ficam no mesmo fluxo rolável. Assim o card de
    // upgrade vem logo depois dos links, sem ser empurrado para o rodapé, e a
    // sidebar continua usável em telas menores.
    flex: "1 1 auto",
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    paddingRight: 0,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    // Mesmo recuo horizontal dos itens de nav (padding-left 11), para o logo
    // alinhar com a coluna de ícones abaixo. padding-top baixo para a nav não
    // ser empurrada para baixo.
    gap: 11,
    paddingLeft: 8,
    paddingTop: 2,
    paddingBottom: 6,
  } satisfies CSSProperties,
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 11,
    minWidth: 0,
    color: "#0A0A0A",
    textDecoration: "none",
  } satisfies CSSProperties,
  brandText: {
    fontFamily: '"Inter Variable", "Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 22,
    lineHeight: "26px",
    fontWeight: 700,
    letterSpacing: "-0.05em",
  } satisfies CSSProperties,
  search: {
    marginTop: 22,
    height: 36,
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxSizing: "border-box",
    border: 0,
    borderRadius: 11,
    padding: "0 10px",
    background: "#F1F1F3",
    color: "#4B5563",
    textAlign: "left",
    boxShadow: "inset 0 0 0 1px rgba(10,10,10,0.06)",
  } satisfies CSSProperties,
  searchText: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 14,
    lineHeight: "18px",
    fontWeight: 600,
    letterSpacing: "-0.03em",
  } satisfies CSSProperties,
  searchBadge: {
    width: 24,
    height: 24,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    background: "#E4E4E7",
    color: "#4B5563",
    fontSize: 15,
    lineHeight: "15px",
    fontWeight: 650,
  } satisfies CSSProperties,
  nav: {
    // Respiro entre o logo e o primeiro item, calibrado para bater com a
    // referência (PagePilot): ~24px no total com o paddingBottom: 6 do header.
    marginTop: 19,
    marginBottom: 6,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 2,
  } satisfies CSSProperties,
  navLinkBase: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxSizing: "border-box",
    borderRadius: 8,
    padding: "7.5px 9px",
    textDecoration: "none",
    fontSize: 14,
    lineHeight: "19px",
    fontWeight: 500,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  // Sub-itens de uma categoria: recuados, com linha vertical à esquerda, um
  // pouco menores que os itens de topo (como na referência).
  subWrap: {
    marginLeft: 17,
    paddingLeft: 12,
    borderLeft: "1.5px solid rgba(10,10,10,0.10)",
    marginTop: 3,
    marginBottom: 3,
    display: "flex",
    flexDirection: "column",
    gap: 1,
  } satisfies CSSProperties,
  navSubLinkBase: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxSizing: "border-box",
    borderRadius: 8,
    padding: "7px 10px",
    textDecoration: "none",
    fontSize: 13.5,
    lineHeight: "18px",
    fontWeight: 500,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  spacer: {
    minHeight: 0,
    flex: 1,
  } satisfies CSSProperties,
  // Bloco inferior no mesmo fluxo da navegação, mas com altura flexível para
  // ancorar os cards finais mais perto do rodapé quando houver espaço.
  footer: {
    flex: "1 0 auto",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    paddingTop: 8,
  } satisfies CSSProperties,
  upgradeCard: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 15,
    padding: "13px 15px 12px",
    marginTop: 0,
    marginBottom: 16,
    background: "linear-gradient(135deg, #BFD3FF 0%, #E6EEFF 62%, #F2F6FF 100%)",
    color: "#0A0A0A",
    boxShadow: "none",
    textAlign: "center",
  } satisfies CSSProperties,
  footerBottom: {
    marginTop: 0,
    paddingTop: 16,
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  fixedBottom: {
    // Fica fora da área rolável de propósito: a rolagem termina no card de
    // upgrade, e daqui para baixo (Sugestões, Ajuda, promos e perfil) o bloco
    // é âncora. Antes o perfil descia junto com a rolagem e sumia da tela.
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    paddingTop: 8,
  } satisfies CSSProperties,
  // Ícone "herói" centralizado no topo do card (sem chip), como na referência.
  upgradeIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 6px",
    color: "#1A1A1A",
  } satisfies CSSProperties,
  upgradeTitle: {
    margin: "0",
    color: "#0A0A0A",
    fontSize: 14,
    lineHeight: "18px",
    fontWeight: 700,
    letterSpacing: "-0.03em",
  } satisfies CSSProperties,
  upgradeCopy: {
    margin: "4px 0 0",
    color: "rgba(10,10,10,0.6)",
    fontSize: 12.2,
    lineHeight: "16px",
    fontWeight: 500,
  } satisfies CSSProperties,
  upgradeButton: {
    marginTop: 11,
    width: "100%",
    height: 32,
    borderRadius: 9,
    fontSize: 12.5,
    fontWeight: 650,
  } satisfies CSSProperties,
  // Blocos promocionais adaptados à Velo (estilo dos cards da referência):
  // ícone colorido à esquerda + título/subtítulo à direita, fundo tonalizado.
  promoCard: {
    width: "100%",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    gap: 8,
    border: 0,
    borderRadius: 11,
    padding: "8px 9px",
    marginBottom: 6,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  promoIcon: {
    width: 32,
    height: 32,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  } satisfies CSSProperties,
  promoTitle: {
    display: "block",
    fontSize: 12.5,
    lineHeight: "16px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "#0A0A0A",
  } satisfies CSSProperties,
  promoSub: {
    display: "block",
    marginTop: 1,
    fontSize: 11,
    lineHeight: "14px",
    fontWeight: 500,
    color: "rgba(10,10,10,0.55)",
  } satisfies CSSProperties,
  profileCard: {
    width: "100%",
    minWidth: 0,
    minHeight: 52,
    display: "flex",
    alignItems: "center",
    gap: 11,
    boxSizing: "border-box",
    border: 0,
    borderRadius: 13,
    padding: "9px 11px",
    background: "transparent",
    color: "#0A0A0A",
    textAlign: "left",
    boxShadow: "inset 0 0 0 1px rgba(10,10,10,0.08)",
  } satisfies CSSProperties,
  avatar: {
    width: 34,
    height: 34,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 999,
    background: "#E4E4E7",
    color: "#4B5563",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  profileText: {
    minWidth: 0,
    flex: 1,
  } satisfies CSSProperties,
  profileName: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "#0A0A0A",
    fontSize: 13,
    lineHeight: "17px",
    fontWeight: 600,
    letterSpacing: "-0.025em",
  } satisfies CSSProperties,
  profileEmail: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    marginTop: 2,
    color: "rgba(10,10,10,0.55)",
    fontSize: 11,
    lineHeight: "14px",
    fontWeight: 500,
  } satisfies CSSProperties,
  profileChevrons: {
    width: 16,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: "rgba(10,10,10,0.5)",
  } satisfies CSSProperties,
  profileWrap: {
    position: "relative",
  } satisfies CSSProperties,
  profileSidePanel: {
    position: "fixed",
    left: 278,
    bottom: 22,
    width: 198,
    boxSizing: "border-box",
    borderRadius: 16,
    padding: 5,
    border: "1px solid rgba(10,10,10,0.08)",
    background: "#FFFFFF",
    color: "#0A0A0A",
    boxShadow: "0 14px 34px rgba(10,10,10,0.14), 0 1px 0 rgba(255,255,255,0.9) inset",
    zIndex: 90,
    transformOrigin: "left bottom",
  } satisfies CSSProperties,
  profileMenuRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
    boxSizing: "border-box",
    border: 0,
    minHeight: 35,
    borderRadius: 11,
    padding: "7px 9px",
    background: "transparent",
    color: "#171717",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  profileMenuRowLeft: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 9,
  } satisfies CSSProperties,
  profileMenuLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12.4,
    lineHeight: "16px",
    fontWeight: 560,
    letterSpacing: "-0.015em",
  } satisfies CSSProperties,
  profileMenuIcon: {
    width: 15,
    height: 15,
    flexShrink: 0,
    color: "rgba(10,10,10,0.74)",
  } satisfies CSSProperties,
  profileMenuDivider: {
    height: 1,
    margin: "5px 6px",
    background: "rgba(10,10,10,0.07)",
  } satisfies CSSProperties,
  profilePanel: {
    position: "absolute",
    left: "calc(100% + 6px)",
    bottom: 0,
    width: 214,
    boxSizing: "border-box",
    borderRadius: 18,
    padding: 4,
    border: "1px solid rgba(10,10,10,0.08)",
    background: "#FFFFFF",
    boxShadow: "0 14px 30px rgba(10,10,10,0.14)",
    zIndex: 80,
  } satisfies CSSProperties,
  profilePanelCard: {
    overflow: "hidden",
    borderRadius: 15,
    border: "1px solid rgba(10,10,10,0.06)",
    background: "#FFFFFF",
    boxShadow: "inset 0 1px 0 rgba(10,10,10,0.02)",
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", "Segoe UI", sans-serif',
  } satisfies CSSProperties,
  profilePanelBody: {
    padding: "7px 6px 4px",
  } satisfies CSSProperties,
  profilePanelRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
    boxSizing: "border-box",
    border: 0,
    minHeight: 40,
    borderRadius: 11,
    padding: "8px 10px",
    background: "transparent",
    color: "#1A1A1A",
    textAlign: "left",
  } satisfies CSSProperties,
  profilePanelRowActive: {
    background: "rgba(10,10,10,0.06)",
  } satisfies CSSProperties,
  profilePanelRowLeft: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  profilePanelRowLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 10.5,
    lineHeight: "14px",
    fontWeight: 500,
    letterSpacing: "-0.015em",
  } satisfies CSSProperties,
  profilePanelIcon: {
    width: 14,
    height: 14,
    flexShrink: 0,
    color: "rgba(10,10,10,0.8)",
  } satisfies CSSProperties,
  profilePanelDivider: {
    height: 1,
    margin: "3px 0",
    background: "rgba(10,10,10,0.08)",
  } satisfies CSSProperties,
  profilePanelFooter: {
    padding: "1px 6px 6px",
  } satisfies CSSProperties,
  profilePanelBadge: {
    height: 15,
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    borderRadius: 999,
    padding: "0 5px",
    fontSize: 7.5,
    lineHeight: "9px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    background: "rgba(37,99,235,0.1)",
    color: "#1D4ED8",
    boxShadow: "inset 0 0 0 1px rgba(37,99,235,0.14)",
  } satisfies CSSProperties,
  profilePanelMutedBadge: {
    height: 15,
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    padding: "0 5px",
    fontSize: 7.5,
    lineHeight: "9px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    background: "rgba(10,10,10,0.06)",
    color: "rgba(10,10,10,0.6)",
  } satisfies CSSProperties,
  profilePanelCircleButton: {
    width: 16,
    height: 16,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    background: "rgba(10,10,10,0.06)",
    color: "rgba(10,10,10,0.6)",
    boxShadow: "inset 0 0 0 1px rgba(10,10,10,0.06)",
  } satisfies CSSProperties,
  // ── Modal de configurações (aberto pela área de perfil) ──────────────────
  settingsOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 120,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    background: "rgba(10,10,10,0.45)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
  } satisfies CSSProperties,
  settingsModal: {
    width: "100%",
    maxWidth: 380,
    boxSizing: "border-box",
    borderRadius: 20,
    border: "1px solid rgba(10,10,10,0.08)",
    background: "#FFFFFF",
    boxShadow: "0 24px 60px rgba(10,10,10,0.28)",
    overflow: "hidden",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", sans-serif',
  } satisfies CSSProperties,
  settingsHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 16px 14px",
    borderBottom: "1px solid rgba(10,10,10,0.07)",
  } satisfies CSSProperties,
  settingsBody: {
    padding: 8,
  } satisfies CSSProperties,
  settingsRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    boxSizing: "border-box",
    border: 0,
    minHeight: 44,
    borderRadius: 12,
    padding: "10px 12px",
    background: "transparent",
    color: "#1A1A1A",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  settingsRowLeft: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 11,
  } satisfies CSSProperties,
  settingsRowLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 13.5,
    lineHeight: "18px",
    fontWeight: 550,
    letterSpacing: "-0.01em",
  } satisfies CSSProperties,
  settingsIcon: {
    width: 17,
    height: 17,
    flexShrink: 0,
    color: "rgba(10,10,10,0.75)",
  } satisfies CSSProperties,
  settingsClose: {
    width: 30,
    height: 30,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    border: 0,
    background: "rgba(10,10,10,0.05)",
    color: "rgba(10,10,10,0.6)",
    cursor: "pointer",
  } satisfies CSSProperties,
  settingsDivider: {
    height: 1,
    margin: "6px 8px",
    background: "rgba(10,10,10,0.07)",
  } satisfies CSSProperties,
};
