// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.5";

// src/lib/mcp/tools/list-tables.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { ToolError } from "npm:@lovable.dev/mcp-js@3.0.5";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function adminClient(ctx) {
  if (!ctx.isAuthenticated()) throw new ToolError("N\xE3o autenticado.");
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.rpc("is_admin");
  if (error) throw new ToolError(`Falha ao verificar permiss\xE3o: ${error.message}`);
  if (data !== true) throw new ToolError("Apenas administradores da Velo podem usar estas ferramentas.");
  return supabase;
}
var READABLE_TABLES = [
  "affiliate_applications",
  "affiliate_clicks",
  "affiliate_conversions",
  "affiliate_withdrawal_requests",
  "affiliate_withdrawal_items",
  "affiliates",
  "atlas_usage_logs",
  "catalog_products",
  "category_mapping",
  "dropship_order_events",
  "dropship_orders",
  "dropship_worker_alerts",
  "feature_suggestions",
  "help_articles",
  "help_categories",
  "help_feed_posts",
  "landing_events",
  "ml_compliance_fixes",
  "ml_dimension_fixes",
  "ml_publish_errors",
  "ml_republication_log",
  "ml_seller_readiness",
  "mobile_home_events",
  "notifications",
  "orders",
  "payment_incidents",
  "pending_publications",
  "profiles",
  "referral_rewards",
  "referrals",
  "refund_requests",
  "sales_reports",
  "store_orders",
  "store_reviews",
  "subscription_migrations",
  "subscriptions",
  "support_ai_messages",
  "support_escalations",
  "support_messages",
  "support_tickets",
  "tiktok_events",
  "tiktok_shop_publications",
  "user_page_views",
  "user_products",
  "user_projects",
  "user_publications",
  "user_roles",
  "user_sessions",
  "validapay_webhook_events"
];
var READ_REPORTS = [
  "rpc_admin_cohort_entry",
  "rpc_admin_cohort_funnel",
  "rpc_admin_error_breakdown",
  "rpc_admin_exit_pages",
  "rpc_admin_full_funnel",
  "rpc_admin_landing_funnel",
  "rpc_admin_paid_not_published",
  "rpc_admin_paid_not_published_summary",
  "rpc_admin_paid_without_seller",
  "rpc_admin_paid_without_seller_cohort",
  "rpc_admin_paying_daily",
  "rpc_admin_refund_reasons",
  "rpc_admin_signup_funnel",
  "rpc_admin_store_sales",
  "rpc_admin_top_pages",
  "rpc_admin_traffic_daily",
  "rpc_admin_affiliates_summary",
  "rpc_admin_affiliate_applications",
  "rpc_admin_affiliate_details",
  "rpc_admin_withdrawal_requests",
  "rpc_atlas_usage_summary",
  "rpc_active_subscribers_count",
  "rpc_landing_stats"
];

// src/lib/mcp/tools/list-tables.ts
var list_tables_default = defineTool({
  name: "list_tables",
  title: "Listar tabelas e relat\xF3rios",
  description: "Lista as tabelas da Velo e os relat\xF3rios administrativos que podem ser consultados.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    await adminClient(ctx);
    const payload = { tables: [...READABLE_TABLES], reports: [...READ_REPORTS] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/query-table.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z } from "npm:zod@^3.25.76";
var filterSchema = z.object({
  column: z.string().regex(/^[a-z_][a-z0-9_]*$/),
  op: z.enum(["eq", "neq", "gt", "gte", "lt", "lte", "ilike", "is", "in"]),
  value: z.union([z.string(), z.number(), z.boolean(), z.null(), z.array(z.union([z.string(), z.number()]))])
});
var query_table_default = defineTool2({
  name: "query_table",
  title: "Consultar tabela",
  description: "L\xEA linhas de uma tabela da Velo com filtros, ordena\xE7\xE3o e limite (somente leitura). Use count_only para contar.",
  inputSchema: {
    table: z.enum(READABLE_TABLES),
    columns: z.string().default("*").describe("Colunas separadas por v\xEDrgula, ex: 'id,email,plan'."),
    filters: z.array(filterSchema).max(10).default([]),
    order_by: z.string().regex(/^[a-z_][a-z0-9_]*$/).optional(),
    ascending: z.boolean().default(false),
    limit: z.number().int().min(1).max(500).default(50),
    offset: z.number().int().min(0).default(0),
    count_only: z.boolean().default(false)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const supabase = await adminClient(ctx);
    let q = supabase.from(input.table).select(input.count_only ? "*" : input.columns, input.count_only ? { count: "exact", head: true } : { count: "exact" });
    for (const f of input.filters) {
      if (f.op === "in") {
        if (!Array.isArray(f.value)) throw new ToolError2("O filtro 'in' precisa de uma lista.");
        q = q.in(f.column, f.value);
      } else if (f.op === "is") {
        q = q.is(f.column, f.value);
      } else {
        q = q[f.op](f.column, f.value);
      }
    }
    if (!input.count_only) {
      if (input.order_by) q = q.order(input.order_by, { ascending: input.ascending });
      q = q.range(input.offset, input.offset + input.limit - 1);
    }
    const { data, error, count } = await q;
    if (error) throw new ToolError2(error.message);
    const payload = { count: count ?? null, rows: input.count_only ? [] : data ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }] };
  }
});

// src/lib/mcp/tools/run-report.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.5";
import { z as z2 } from "npm:zod@^3.25.76";
var run_report_default = defineTool3({
  name: "run_report",
  title: "Rodar relat\xF3rio administrativo",
  description: "Executa um relat\xF3rio administrativo somente leitura da Velo (funis, coortes, pagantes sem publicar, reembolsos etc.).",
  inputSchema: {
    report: z2.enum(READ_REPORTS),
    args: z2.record(z2.union([z2.string(), z2.number(), z2.boolean(), z2.null()])).default({}).describe('Par\xE2metros do relat\xF3rio, ex: {"p_days": 30}.')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ report, args }, ctx) => {
    const supabase = await adminClient(ctx);
    const { data, error } = await supabase.rpc(report, args);
    if (error) throw new ToolError3(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? null) }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nqzpoioxvbqavrtphtoa";
var mcp_default = defineMcp({
  name: "velo",
  title: "Velo",
  version: "0.1.0",
  instructions: "Ferramentas administrativas somente leitura da Velo. Use list_tables para ver o que existe, query_table para ler e contar linhas com filtros, e run_report para relat\xF3rios de funil, coortes e pagantes. Exige conta admin.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tables_default, query_table_default, run_report_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.5/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
