ALTER TABLE public.affiliates
  ADD COLUMN IF NOT EXISTS ref TEXT,
  ADD COLUMN IF NOT EXISTS link TEXT,
  ADD COLUMN IF NOT EXISTS commission_rate NUMERIC DEFAULT 20,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();