// This file was originally auto-generated by Lovable.
// Ajuste local: permitir rodar o site sem Supabase (modo "desativado") quando as envs não existirem.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqzpoioxvbqavrtphtoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xenBvaW94dmJxYXZydHBodG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNDMyNDgsImV4cCI6MjA5MDgxOTI0OH0.G1VlS8doiHQtooC2tyiiHbWl4h9kqoMSuirShDhhjzk";
const SUPABASE_DISABLED =
  import.meta.env.VITE_DISABLE_SUPABASE === 'true' || !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

const disabledError = {
  message:
    'Supabase está desativado neste ambiente de desenvolvimento (faltam VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY).',
};

let warned = false;
function warnOnce() {
  if (warned) return;
  warned = true;
  // eslint-disable-next-line no-console
  console.warn(disabledError.message);
}

function disabledPromise<T extends Record<string, any>>(data: T) {
  warnOnce();
  return Promise.resolve({ data, error: disabledError } as any);
}

function createDisabledSupabaseClient() {
  const subscription = { unsubscribe: () => {} };

  const realtimeChannel = {
    on: () => realtimeChannel,
    subscribe: () => realtimeChannel,
  };

  const query = {
    select: () => query,
    eq: () => query,
    in: () => query,
    update: () => query,
    insert: () => query,
    delete: () => query,
    single: () => disabledPromise({}),
    maybeSingle: () => disabledPromise({}),
    then: (onFulfilled: any, onRejected: any) => disabledPromise({}).then(onFulfilled, onRejected),
  };

  return {
    auth: {
      getSession: () => disabledPromise({ session: null }),
      getUser: () => disabledPromise({ user: null }),
      onAuthStateChange: () => {
        warnOnce();
        return { data: { subscription }, error: null } as any;
      },
      signOut: () => disabledPromise({}),
      signInWithPassword: () => disabledPromise({}),
      signInWithOAuth: () => disabledPromise({}),
      signUp: () => disabledPromise({}),
      resetPasswordForEmail: () => disabledPromise({}),
      updateUser: () => disabledPromise({}),
      setSession: () => disabledPromise({}),
      exchangeCodeForSession: () => disabledPromise({}),
    },
    from: () => query,
    functions: {
      invoke: () => disabledPromise({}),
    },
    channel: () => {
      warnOnce();
      return realtimeChannel as any;
    },
    removeChannel: () => disabledPromise({}),
  } as any;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SUPABASE_DISABLED
  ? createDisabledSupabaseClient()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });

export const isSupabaseEnabled = !SUPABASE_DISABLED;
export const supabaseUrl = SUPABASE_URL;
