// This file was originally auto-generated by Lovable.
// Ajuste local: permitir rodar o site sem Supabase (modo "desativado") quando as envs não existirem.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqzpoioxvbqavrtphtoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xenBvaW94dmJxYXZydHBodG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNDMyNDgsImV4cCI6MjA5MDgxOTI0OH0.G1VlS8doiHQtooC2tyiiHbWl4h9kqoMSuirShDhhjzk";
const SUPABASE_DISABLED =
  import.meta.env.VITE_DISABLE_SUPABASE === 'true' || !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

const disabledError = {
  message:
    'Supabase está desativado neste ambiente de desenvolvimento (faltam VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY).',
};

let warned = false;
function warnOnce() {
  if (warned) return;
  warned = true;
  // eslint-disable-next-line no-console
  console.warn(disabledError.message);
}

function disabledPromise<T extends Record<string, any>>(data: T) {
  warnOnce();
  return Promise.resolve({ data, error: disabledError } as any);
}

function createDisabledSupabaseClient() {
  const subscription = { unsubscribe: () => {} };

  const realtimeChannel = {
    on: () => realtimeChannel,
    subscribe: () => realtimeChannel,
  };

  const query = {
    select: () => query,
    eq: () => query,
    neq: () => query,
    gt: () => query,
    gte: () => query,
    lt: () => query,
    lte: () => query,
    like: () => query,
    ilike: () => query,
    is: () => query,
    in: () => query,
    contains: () => query,
    or: () => query,
    not: () => query,
    filter: () => query,
    match: () => query,
    order: () => query,
    limit: () => query,
    range: () => query,
    update: () => query,
    insert: () => query,
    upsert: () => query,
    delete: () => query,
    single: () => disabledPromise({}),
    maybeSingle: () => disabledPromise({}),
    then: (onFulfilled: any, onRejected: any) => disabledPromise({}).then(onFulfilled, onRejected),
  };

  return {
    auth: {
      getSession: () => disabledPromise({ session: null }),
      getUser: () => disabledPromise({ user: null }),
      onAuthStateChange: () => {
        warnOnce();
        return { data: { subscription }, error: null } as any;
      },
      signOut: () => disabledPromise({}),
      signInWithPassword: () => disabledPromise({}),
      signInWithOAuth: () => disabledPromise({}),
      signUp: () => disabledPromise({}),
      resetPasswordForEmail: () => disabledPromise({}),
      updateUser: () => disabledPromise({}),
      refreshSession: () => disabledPromise({ session: null }),
      setSession: () => disabledPromise({}),
      exchangeCodeForSession: () => disabledPromise({}),
    },
    from: () => query,
    functions: {
      invoke: () => disabledPromise({}),
    },
    channel: () => {
      warnOnce();
      return realtimeChannel as any;
    },
    removeChannel: () => disabledPromise({}),
  } as any;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SUPABASE_DISABLED
  ? createDisabledSupabaseClient()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });

export const isSupabaseEnabled = !SUPABASE_DISABLED;
export const supabaseUrl = SUPABASE_URL;

type SupabaseResultWithError = { error: unknown; data?: unknown; count?: number | null };

const JWT_EXPIRED_MESSAGES = ["jwt expired", "token is expired", "invalid jwt"];
const SESSION_REFRESH_WINDOW_MS = 60_000;
let sessionRefreshPromise: Promise<void> | null = null;

export const isJwtExpiredError = (error: unknown) => {
  if (!error) return false;

  const message =
    typeof error === "string"
      ? error
      : error instanceof Error
        ? error.message
        : typeof error === "object" && "message" in error
          ? String((error as { message?: unknown }).message ?? "")
          : String(error);

  const normalized = message.toLowerCase();
  return JWT_EXPIRED_MESSAGES.some((item) => normalized.includes(item));
};

const refreshOrClearExpiredSession = async () => {
  if (!isSupabaseEnabled) return;

  if (!sessionRefreshPromise) {
    sessionRefreshPromise = supabase.auth
      .refreshSession()
      .then(async ({ error }) => {
        if (!error) return;
        console.warn("[supabase] não foi possível renovar a sessão; limpando token local vencido.", error);
        await supabase.auth.signOut({ scope: "local" });
      })
      .finally(() => {
        sessionRefreshPromise = null;
      });
  }

  await sessionRefreshPromise;
};

export const ensureFreshSupabaseSession = async () => {
  if (!isSupabaseEnabled) return;

  const { data, error } = await supabase.auth.getSession();
  if (error && isJwtExpiredError(error)) {
    await refreshOrClearExpiredSession();
    return;
  }

  const expiresAt = data.session?.expires_at;
  if (!expiresAt) return;

  const msUntilExpiry = expiresAt * 1000 - Date.now();
  if (msUntilExpiry <= SESSION_REFRESH_WINDOW_MS) {
    await refreshOrClearExpiredSession();
  }
};

export const withFreshSupabaseSession = async <T extends SupabaseResultWithError>(
  request: () => PromiseLike<T>,
): Promise<T> => {
  await ensureFreshSupabaseSession();

  const firstResult = await request();
  if (!isJwtExpiredError(firstResult.error)) return firstResult;

  await refreshOrClearExpiredSession();
  return request();
};
